export const exportAsText = (data) => {
  const {
    score,
    skills = [],
    missingSkills = [],
    aiSuggestions = '',
    fileName = '',
    analysisDate = new Date().toISOString()
  } = data;

  const content = `
===========================================
      RESUME ANALYSIS REPORT
===========================================

📅 Generated: ${new Date(analysisDate).toLocaleString()}
📄 Resume: ${fileName || 'Not specified'}

🎯 ATS COMPATIBILITY SCORE
${'='.repeat(30)}
Score: ${score}% ${getScoreStars(score)}
${getScoreInterpretationText(score)}

📊 SKILLS ANALYSIS
${'='.repeat(30)}

✅ SKILLS FOUND (${skills.length}):
${skills.length > 0 ? skills.map(skill => `  • ${skill}`).join('\n') : '  No skills extracted from resume'}

${missingSkills.length > 0 ? `
❌ MISSING SKILLS (${missingSkills.length}):
${missingSkills.map(skill => `  • ${skill}`).join('\n')}
` : ''}

💡 AI RECOMMENDATIONS
${'='.repeat(30)}
${aiSuggestions}

📋 ACTION ITEMS
${'='.repeat(30)}
${getActionItems(score, missingSkills.length)}

✨ QUICK IMPROVEMENT TIPS:
• Use relevant keywords from job description
• Quantify achievements with numbers (e.g., "Increased sales by 30%")
• Keep formatting simple and clean
• Include relevant certifications
• Customize resume for each job application
• Use standard section headers (Experience, Education, Skills)
• Avoid graphics and complex formatting
• Include contact information clearly

${'='.repeat(50)}
Report generated by AI Resume Analyzer
Powered by Groq LLM | MERN Stack Application
For more information, visit your application
${'='.repeat(50)}
  `.trim();

  // Create and download text file
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `resume-analysis-${Date.now()}.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

const getScoreStars = (score) => {
  const filled = '★'.repeat(Math.floor(score / 20));
  const empty = '☆'.repeat(5 - Math.floor(score / 20));
  return `[${filled}${empty}] ${score >= 80 ? 'Excellent' : score >= 60 ? 'Good' : 'Needs Improvement'}`;
};

const getScoreInterpretationText = (score) => {
  if (score >= 80) return 'Your resume is highly compatible with ATS systems!';
  if (score >= 60) return 'Your resume has potential but needs optimization.';
  return 'Your resume needs significant improvements for ATS compatibility.';
};

const getActionItems = (score, missingSkillsCount) => {
  if (score >= 80) {
    return `• Maintain current resume quality
• Continue updating with new skills and experiences
• Keep tailoring resume for specific job applications
• Update regularly with new achievements`;
  } else if (score >= 60) {
    return `• Add ${missingSkillsCount} missing skills to your resume
• Improve formatting and structure
• Quantify achievements with specific numbers
• Match keywords from job description
• Consider adding a professional summary`;
  } else {
    return `• Major revamp needed for ATS compatibility
• Add all ${missingSkillsCount} missing skills
• Match 80%+ keywords from job description
• Improve skill section organization
• Consider professional resume writing services
• Simplify formatting and remove graphics`;
  }
};